pages:
  stage: deploy
  image: node:latest
  script:
    - echo 'Installing dependencies'
    - npm ci
    - echo 'Building Nuxt app'
    - npm run generate
    - echo 'Preparing public directory'
    - mv .output/public public
    - echo 'Contents of public directory:'
    - ls -R public
    - echo 'Size of public directory:'
    - du -sh public
    - echo 'Checking for index.html:'
    - test -f public/index.html && echo "index.html exists" || echo "index.html not found"
  artifacts:
    paths:
      - public
  only:
    - main