pages:
   image: node
   before_script:
      - npm ci --cache .npm --prefer-offline
   script:
      - npm run generate
   cache: # https://docs.gitlab.com/ee/ci/caching/#cache-nodejs-dependencies
      key:
         files:
         - package-lock.json
      paths:
         - .npm/
   artifacts:
      paths:
         - .output/public
   publish: .output/public
   rules:
      - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
